### ISSUE TITLE
Code refactor

### ISSUE THREAD

**Issue by jeremybeal11** [p2pcloud/protocol#28]
We can remove this and make the fee static: 

https://github.com/p2pcloud/protocol/blob/b1304cdc2dd0a5dea3d403ffdb9e21dbdc9bace1/contracts/Broker.sol#L44

 by doing so we can eliminate the `communityOwnable.sol` file for simplicity. 

```
import "./CommunityOwnable.sol";
```

**Comment by containerman17** [comment]
Heard! Fixed

**Comment by jeremybeal11** [comment]
@solohin do you have a link to the PR?
